% This function generate total scatter sinogram by perform
% multiple scatters convolution of the single scatter sinogram.
% Two convolution models are allowed:
%   1) the fixed convolution kernel
%   2) object-dependent convolution kernel (CTAC path length)
% 
% Inputs:
%   dsSinglScatSino:    single scatter sino in downsampled space
%	scanner:            scanner parameters generated by petrecon_scanner.m
%	sinoParams:          acquisition parameters generated by petrecon_acqparams.m
%	dsSinoParams:        down-sampled acquisition geoemtry used in mbscParams
%   dsImParams:
%   mbscParams:         MBSC params
%   dsPathLengthrr:     CTAC path length in downsampled and radial rebinned
%                       space
%   multiScatModel:     multiple scatter convoluiton model
%                       1 - fixed kernel; 2 - object-dependent kernel
%   directSlicesFlag:   flag to perform upsampling only for the direct slices
%
% Outputs:
%	scatSino:           Fully upsampled (to radial repositioned space) total
%                       scatter
