% This function performs spatially variant convolution of
% the single scatter sinogram in the down-sampled domain
%
% Inputs:
%   dsTOFSinglScatSino: single scatter sino in downsampled space
%	scanner:            scanner parameters generated by petrecon_scanner.m
%	acqParams:          acquisition parameters generated by petrecon_acqparams.m
%	dsAcqParams:        down-sampled acquisition geoemtry used in mbscParams
%   mbscParams:         MBSC params
%
%
% Outputs:
%   dsTotalTOFscatterUpPhi: down sampled total TOF scatter sinograms except
%                           the dims of time bins and inplane views
%	nontofScatter3d:    Fully upsampled (to radial repositioned space) total
%                       nontof scatter
%
