

% Matlab code generated by 'parseTriggers.py' based on 'resp-trig-0.txt'
% All msec values are zero relative to the first timestamp in the list file: 7752
% Ref: HDF5 list file at '/HeaderData/ListHeader/firstTmAbsTimeStamp'
% triggerCnt=75, triggerIntervals=74
