



% Matlab code generated by 'testUnlistParseTriggers.py' script.
% To generate startMsecVec and endMsecVec values, each start/end row vector specifies one gated frame
% zero msec value corresponds to first time marker in list file (ref: /HeaderData/ListHeader/firstTmAbsTimeStamp)
