function [params] = default_reconParams(count) 

if isempty(count) 
    count = 10000; 
end 

params = struct('SimName',['ANONa' num2str(count)],...
                'SeriesDesc','LSTV1 Reconstruction',...
                'nXdim',256,...
                'nYdim',256,...
                'nZdim',47,...
                'Algorithm','TOFOSEM',...
                'Subsets',24,...
                'Iterations',2,...
                'FilterFWHM',6.4,...
                'zfilter',2,...
                'beta',350,...
                'PSFModel',100,...
                'ScatterCorr',1,...
                'RandomsCorr',1,...
                'AttenCorr',1,...
                'DeadTimeCorr',1,...
                'DurationCorr',1,...
                'DecayCorr',1); 
end 