% defaultReconParams - Initialize the reconstruction structure with
% default field values.
%
% Usage:
% params = defaultReconParams
%
% Typically, this is only for generating the structure and the required
% values are overwritten.
%
% See also: LesionSynthesisToolbox

% By Ran Klein, The Ottawa Hospital, 2022

function params = defaultReconParams

params = struct('SimName','UnspecifiedReconName',...
                'SeriesDesc','LSTV1 Reconstruction',...
                'nXdim',256,...
                'nYdim',256,...
                'nZdim',47,...
                'Algorithm','TOFOSEM-PSF',...
                'Subsets',24,...
                'Iterations',2,...
                'FilterFWHM',6.4,...
                'zfilter',2,...
                'beta',350,...
                'PSFModel',100,...
                'ScatterCorr',1,...
                'RandomsCorr',1,...
                'AttenCorr',1,...
                'DeadTimeCorr',1,...
                'DurationCorr',1,...
                'DecayCorr',1,...
				'ReconToolbox','DUETTO'); 
end 