% runLesionInsertionPlusRecon_WebApp - main PET lesion insertion wrapper for 
% the Lesion Syntesis Toolbox (LST) webapp. The required lesion synthesis 
% parameters previously generated by the LST webapp are contained in a 
% proprietary parameters file (lesionParamsFile) that referes to all
% required data files in predefined directories.
%
% Lesion Synthesis at this time is only supported using the GE DUETTO  
% TOOLOX. For development/modifications/access to source code please contact 
% GE Healthcare PET image reconstrcution development team 
% (As of early 2023: Michael.Spohn@gehealthcare.com and/or Elizabeth.Philps@gehealthcare.com)
%
% This function uses tools from the GE DUETTO TOOLBOX and
% therefore needs DUETTO in the file path.
%
% Usage: 
% ======
% runLesionInsertionPlusRecon(lesionParamsFile)
%
% Next Steps: userConfig = ptbUserConfig(info.reconParams.Algorithm);, LesionInsertionDUETTO_WebApp,
%
% Author: Hanif Gabrani-Juma, B.Eng, MASc (2019)
% Created: 2018
% Last Modified: April 30 2019
%
% Heavily modified by Ran Klein, The Ottawa Hospital, 2022

function runLesionInsertionPlusRecon_WebApp(lesionParamsFile)

load(lesionParamsFile, 'info')
patDataDir = info.patDataDir;
simulationName = info.reconName;
% baseDir = [info.simulationDir filesep info.patientID ' - ' simulationName]; 
baseDir = fileparts(lesionParamsFile);

if ~isfield(info,'simulationArchiveDir') || isempty(info.simulationArchiveDir)
	disp('No archive directory provided. Leaving results in the simulation directory');
	archiveDataFlag = false;
	archiveDir = '';
else
	archiveDir = info.simulationArchiveDir;
	if ~exist(archiveDir,'dir')
		mkdir(archiveDir)
	end
	disp(['Final results will be archiving to ' archiveDir filesep simulationName '. Intermediate files will be deleted']);
	archiveDataFlag = true;
end


% Typically used for debugging or when the system crashes mid synthesis 
LIparams.copyFiles = 'auto'; % yes you want to copy the files over 
LIparams.baselineRecon = 'auto'; % {'yes','no','auto'}
LIparams.genLesionFiles = 1; % Yes I want to generate the lesion projections
LIparams.LesionBedPosRecon = []; % reconstruct only the bed positions associated with the lesions - otherwise all bed positions.

% Run Lesion Insertion
% status = LesionInsertionTOF_WebApp(simulationName, lesionParamsFile, patDataDir, LIparams, baseDir, archiveDir);
status = LesionInsertionDUETTO_WebApp(simulationName, lesionParamsFile, patDataDir, LIparams, baseDir, archiveDir);

% change directory to avoid error trying to remove this directory
cd(info.simulationDir);

%% Finalize and archive results files 
if archiveDataFlag
	% Fix the DICOM files first
	dirIn = [baseDir filesep 'reconWithLesion' filesep, info.simParams.SeriesDesc];
	dirOut = [archiveDir filesep simulationName filesep info.reconProfile '_DICOM'];
	mkdir(dirOut)
	fixGEReconDICOMOutput(dirIn, dirOut)
	
	% Fix the mat file second as the header comes from the DICOM series
	makefIR3DmatFile([baseDir filesep 'reconWithLesion'], [archiveDir filesep simulationName filesep info.reconProfile '_fIR3D.mat']);

	% Move the lesion parameters file
	movefile(lesionParamsFile, [archiveDir filesep simulationName filesep info.reconProfile '_LesionParams.mat']);

	if isfield(status,'CTlesionSynthesis') && status.CTlesionSynthesis
		copyfile([baseDir filesep 'reconWithLesion' filesep 'CTAC_DICOM'], [archiveDir filesep simulationName filesep 'CTAC_DICOM']);
		movefile([baseDir filesep 'reconWithLesion' filesep 'CTAC.mat'],[archiveDir filesep simulationName]);
	end

	% Send results to DICOM node
	if isfield(info,'DICOMSend') && ~isempty(info.DICOMSend.TargetAET)
		sendCmd = ['"' which('storescu.exe') '" -aet ' info.DICOMSend.SourceAET ' -aec ' info.DICOMSend.TargetAET ' -v ' info.DICOMSend.TargetHost ' ' num2str(info.DICOMSend.TargetPort) ' '];
		disp('Sending lesion PET to DICOM:')
		disp(sendCmd)
		[status, response] = system([sendCmd '+sd "' dirOut '"']);
		disp('DICOM send response:')
		disp(response);
		if info.DICOMSend.IncludeCT
			disp('Sending CT data to DICOM:')
			disp(sendCmd)
			[status, response] = system([sendCmd '+sd "' baseDir filesep 'reconWithLesion' filesep 'CTAC_DICOM"']);
			disp('DICOM send response:')
			disp(response);
		end
	end	
	
	% Clean up temporary directory
	rmdir(baseDir,'s')

else % Don't archive the data - leave at all where it was processed   TO DO: not tested
	
	% Reorganize the data
	% Projections - TO DO: Don't want to keep these
	for i = 1:20
		projName = [baseDir filesep simulationName filesep 'reconWithLesion',...
			filesep 'LesionProjs_frame' num2str(i)];
		if exist(projName,'file')
			movefile(projName,...
				[baseDir filesep simulationName]);
			disp('Archived simulated projections')
			disp(projName)
		end
	end

	% Volumetric image
	reconMatFilename = [baseDir filesep simulationName filesep 'reconWithLesion',...
		filesep 'ir3d.sav'];
	
	if exist(reconMatFilename,'file')
		movefile(reconMatFilename,...
			[baseDir filesep simulationName]);
		disp('Archived recon sav file')
		disp(reconMatFilename)
	end


	% Lesion data DICOM series without fixing data
	reconDICOMDir = [baseDir filesep simulationName filesep 'reconWithLesion',...
		filesep 'Synthetic_Lesion_Offline_3D'];
	
	if exist(reconDICOMDir,'dir')
		movefile(reconDICOMDir,...
			[baseDir filesep simulationName]);
		disp('Archived recon DICOM files')
		disp(reconDICOMDir)
	end

	% instruction for reconstruction of lesion data - redundant with
	% lesionParams file.
	reconParamsFilename = [baseDir filesep simulationName filesep 'reconWithLesion',...
		filesep 'reconParams.mat'];
	
	if exist(reconParamsFilename,'file')
		movefile(reconParamsFilename,...
			[baseDir filesep simulationName]);
		disp('Archived recon sav file')
		disp(reconParamsFilename)
	end
	
end

end
